### PR TITLE
Start/stop button

### PR DESCRIPTION
**Pull request by gomorizsolt**
Issue #4 and #9.

Changes:
- implemented the periodic message's start/stop button functionality.

As a part of the PR, the requirements in #9 has also been completed.

### CODE REVIEW

**Review by thisismydesign — APPROVED** [review]
Looks good. One thing though, the periodic data sending should not be turned on if I edit the message. It should always be off unless explicitly started.

**Comment by gomorizsolt** [comment]
That makes sense, thanks. Will be fixed soon.

**Comment by gomorizsolt** [comment]
As @thisismydesign pointed out in the previous comment - and also after clarifying the exact/desired behavior -, the flow has been slightly modified:
- the periodic message's `Submit` button is completely independent from the start/stop buttons, thereby changing the input also affects the message that the clients receive,
- abbreviated/refactored the code(e.g. removed the unnecessary `objectIsNotEmpty` function from both BE and FE).

Could anyone also try the [**deployed**](https://c-hive-ws.herokuapp.com/) version out in order to verify that the features work as expected/described?

Let me know if something is either missing or is unclear.

**Comment by bencevoros** [comment]
It looks good to me excluding these:
image

**Comment by gomorizsolt** [comment]
> It looks good to me excluding these:
> image

Whoops, left those non-existing functions in `index.html`, thanks!

**Review by thisismydesign — APPROVED** [review]

**Pull request merged**
